import type { TranscriptMessage } from '@lst/protocol';

/**
 * A deterministic subtitle script used by the Phase 0 mock session.
 *
 * Each segment is emitted as a sequence of revisions: growing `partial`
 * revisions (no translation yet), then one `final` revision that carries
 * the translation. This exercises the receiver's segmentId/revision rules.
 */
export interface MockSegment {
  segmentId: string;
  startMs: number;
  endMs: number;
  /** Progressive partial texts, in order. */
  partials: string[];
  finalText: string;
  translatedText: string;
}

export const MOCK_SEGMENTS: readonly MockSegment[] = [
  {
    segmentId: 'seg-001',
    startMs: 0,
    endMs: 2600,
    partials: ['Welcome', 'Welcome to the live'],
    finalText: 'Welcome to the live subtitle demo.',
    translatedText: '欢迎来到实时字幕演示。',
  },
  {
    segmentId: 'seg-002',
    startMs: 2600,
    endMs: 5400,
    partials: ['This text is', 'This text is generated by'],
    finalText: 'This text is generated by the local mock backend.',
    translatedText: '这段文字由本地模拟后端生成。',
  },
  {
    segmentId: 'seg-003',
    startMs: 5400,
    endMs: 7800,
    partials: ['No real speech'],
    finalText: 'No real speech recognition is running yet.',
    translatedText: '目前还没有运行真正的语音识别。',
  },
  {
    segmentId: 'seg-004',
    startMs: 7800,
    endMs: 10200,
    partials: ['Your video audio', 'Your video audio should still'],
    finalText: 'Your video audio should still be audible.',
    translatedText: '你的视频声音应该仍然可以听到。',
  },
  {
    segmentId: 'seg-005',
    startMs: 10200,
    endMs: 12000,
    partials: ['Stopping the session'],
    finalText: 'Stopping the session removes this overlay.',
    translatedText: '停止会话后这个字幕层会被移除。',
  },
];

export type ScriptEvent = Omit<TranscriptMessage, 'sessionId'>;

/**
 * Flatten the segments into an ordered list of transcript events.
 * The list is deterministic: same input → same output.
 */
export function buildScriptEvents(segments: readonly MockSegment[] = MOCK_SEGMENTS): ScriptEvent[] {
  const events: ScriptEvent[] = [];
  for (const segment of segments) {
    let revision = 0;
    for (const partial of segment.partials) {
      events.push({
        type: 'transcript',
        segmentId: segment.segmentId,
        revision: revision++,
        status: 'partial',
        startMs: segment.startMs,
        sourceText: partial,
      });
    }
    events.push({
      type: 'transcript',
      segmentId: segment.segmentId,
      revision: revision,
      status: 'final',
      startMs: segment.startMs,
      endMs: segment.endMs,
      sourceText: segment.finalText,
      translatedText: segment.translatedText,
    });
  }
  return events;
}
